# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.

github: [metadata]
title: A Hackermouse's Guide Through Cyberspace
description: >- # this means to ignore newlines until "baseurl:"
  Cyberblog with infographics on hardware security, side-channel analysis, artficial intelligence and cryptography.
baseurl: "/hackermouses-guide-through-cyberspace" # the subpath of your site, e.g. /blog
url: "https://bruteforcemisa.github.io" # the base hostname & protocol for your site, e.g. http://example.com

github_username:  BruteforceMisa

# Build settings
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "hackermouse"
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme


# Site Author
author:
  name             : "BruteforceMisa"
  avatar           : "/assets/images/Misa.jpeg"
  bio              : "Hackermouse with Cheesebook"
  location         : "Cyberspace"
  email            :
  links:
    - label: "Drawing credits: @doodledoobug"
      icon: "fa-solid fa-pencil"
      url: "https://doodledoobug.carrd.co"

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid 
  path: /tags/

# Paginate
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/


# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      share: false
      related: false



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
